#################################
#   Picom — Catppuccin Mocha
#################################

# Backend
backend = "glx";
vsync = true;

# Esquinas redondeadas
corner-radius = 10;
rounded-corners-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'"
];

# Sombras
shadow = true;
shadow-radius = 16;
shadow-opacity = 0.45;
shadow-offset-x = -16;
shadow-offset-y = -16;
shadow-color = "#11111b";
shadow-exclude = [
  "name = 'Notification'",
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "_GTK_FRAME_EXTENTS@:c"
];

# Transparencia (sutil)
inactive-opacity = 0.95;
active-opacity = 1.0;
frame-opacity = 1.0;
inactive-opacity-override = false;
inactive-dim = 0.0;

# Excluir de la transparencia (no afectar polybar/fullscreen)
opacity-rule = [
  "100:fullscreen",
  "100:class_g = 'polybar'"
];

# Difuminado detrás de ventanas translúcidas
blur-method = "dual_kawase";
blur-strength = 4;
blur-background = true;
blur-background-frame = true;
blur-background-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "_GTK_FRAME_EXTENTS@:c"
];

# Animaciones de aparición/desaparición
fading = true;
fade-in-step = 0.04;
fade-out-step = 0.04;
fade-delta = 5;

# Generales
detect-rounded-corners = true;
detect-client-opacity = true;
detect-transient = true;
use-damage = true;
